import {readFile,readdir,access} from 'node:fs/promises';
import {dirname,join,resolve} from 'node:path';
const root=resolve('.');
async function walk(dir){return (await readdir(dir,{withFileTypes:true})).flatMap(entry=>entry.isDirectory()&&!['.git','node_modules'].includes(entry.name)?[]:[join(dir,entry.name)]);}
async function htmlFiles(dir){const out=[];for(const entry of await readdir(dir,{withFileTypes:true})){const file=join(dir,entry.name);if(entry.isDirectory()&&!['.git','node_modules'].includes(entry.name))out.push(...await htmlFiles(file));else if(entry.name.endsWith('.html'))out.push(file)}return out}
const files=await htmlFiles(root),errors=[],titles=new Map(),canonicals=new Map();
for(const file of files){const html=await readFile(file,'utf8');const rel=file.slice(root.length+1);for(const token of ['<title>','name="description"','rel="canonical"','property="og:title"','name="twitter:card"','<h1','application/ld+json'])if(!html.includes(token))errors.push(`${rel}: missing ${token}`);const title=html.match(/<title>(.*?)<\/title>/s)?.[1];if(title){if(titles.has(title))errors.push(`${rel}: duplicate title with ${titles.get(title)}`);titles.set(title,rel)}const canonical=html.match(/rel="canonical" href="([^"]+)"/)?.[1];if(canonical){if(canonicals.has(canonical))errors.push(`${rel}: duplicate canonical`);canonicals.set(canonical,rel)}for(const match of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{JSON.parse(match[1])}catch(error){errors.push(`${rel}: invalid JSON-LD: ${error.message}`)}}for(const match of html.matchAll(/(?:href|src)="([^"#]+)"/g)){const ref=match[1];if(/^(https?:|mailto:|tel:|data:)/.test(ref))continue;const target=resolve(dirname(file),ref.split('?')[0]);try{await access(target)}catch{try{await access(join(target,'index.html'))}catch{errors.push(`${rel}: broken local reference ${ref}`)}}}}
for(const required of ['robots.txt','sitemap.xml','llms.txt','site.webmanifest','assets/vaultwave-official-logo.png','assets/vaultwave-social-card.png'])try{await access(join(root,required))}catch{errors.push(`missing required file ${required}`)}
if(files.length!==11)errors.push(`expected 11 HTML pages, found ${files.length}`);
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`Validated ${files.length} HTML pages, ${titles.size} unique titles, ${canonicals.size} unique canonicals, JSON-LD, local links and required crawler assets.`);
